version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mynetwork
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongodb_data:/data/db

  app:
    image: isahilsundrani/basix
    container_name: node_app
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_USER: admin
      MONGO_PASS: password
      MONGO_DB: mydatabase
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

networks:
  mynetwork:

volumes:
  mongodb_data:
    external: true